# -*- coding: utf-8 -*-
"""LinkExtractorFile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YMAZHK3d7r2EkVKq5kUBnSY637GD91qT
"""



"""##Links extraction File"""

# !sudo apt-get install tesseract-ocr

# !pip install pytesseract


import cv2
import pytesseract as tess
import numpy as np

file_path= r'D:\hackathon\ml_feature\picture.png'

img= cv2.imread(file_path)
gray_img= cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
gray_img, img_bin= cv2.threshold(gray_img,128,255,cv2.THRESH_BINARY | cv2.THRESH_OTSU)

gray_img = cv2.bitwise_not(img_bin)

kernel = np.ones((2, 1), np.uint8)
img = cv2.erode(gray_img, kernel, iterations=1)
img = cv2.dilate(img, kernel, iterations=1)
out_below = tess.image_to_string(img)
# print("OUTPUT:", out_below)

print(out_below)

# !pip install idna
# !pip install uritools
# !pip install platformdirs
# !pip install dnspython

# !pip install tox

# !pip install urlextract

from urlextract import URLExtract

extractor = URLExtract()
urls = extractor.find_urls(out_below)
print(urls)