# -*- coding: utf-8 -*-
"""NumericalData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZcmNKg4_n22L3-FWwOtH9gDjPKdyXjeP
"""



"""##Numerical Data File

"""

pip install git+https://github.com/faustomorales/keras-ocr.git#egg=keras-ocr

pip install keras-ocr

import keras_ocr

import cv2

# img= cv2.imread("/content/Screenshot_20221117_102401.png")

pipeline = keras_ocr.pipeline.Pipeline()

path= "/content/Screenshot_20221117_102401.png"
pred= pipeline.recognize([keras_ocr.tools.read(path)])

pred1= pred[0]

data=[]
box1=[]

for text,box in pred1:
  data.append(text)
  # box1.append(box)

print(data)
# dummy_data= data
# dummy_data.append('twenty')
# print(box1)

lis=['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety','hundred','thousand','lakh','crore','arab','million','billion','trillion']

# print(data.index('twenty'))

# print(data[186])

num= []

for word in data:
  if word in lis:
    num.append(word)

print(num)



